# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/about-packaging-with-github-actions

name: Publish NuGet Package

on:
  push:
    tags:
      - "v*"
    branches:
      - "release/*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-restore --verbosity normal

      - name: Pack NuGet Package
        run: dotnet pack TaskBoard.Framework.Core/TaskBoard.Framework.Core.csproj --configuration Release --no-restore --output nupkg

      - name: Publish to GitHub Packages
        run: dotnet nuget push nupkg/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
